# Generated by Django 3.2.7 on 2021-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
