# Generated by Django 3.2.7 on 2021-10-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0002_alter_game_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turns',
            new_name='Turn',
        ),
    ]
